### ISSUE TITLE
Issues with Nahuatl

### ISSUE THREAD

**Issue by AnnaKatharinaD** [jdellert/lextyp2023#1]
Hi all, 
a couple issues that came up for me so far:

1.  Can 'for a hen to brood' be assumed to be equivalent to 'for a hen to cover her little chicks with her wings'?
2. What does 'to cover honor or admiration for oneself' actually mean? Maybe ADMIRE_SELF?
3. I have some words for covering or hiding something from something else e.g.  'to conceal oneself by day, to protect oneself from the sun' or 'to shelter, or cover something from the wind' and I'm unsure if I should add a new role for COVER (4 'cover from') or create a new frame for these.

If you have thoughts on any of these, please share them.
Anna

**Comment by jdellert** [comment]
Just using this as an alternative communication channel: could I ask you to check your university mail?
